#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQCrud
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TSQL")]
	public partial class TSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSupplier(Supplier instance);
    partial void UpdateSupplier(Supplier instance);
    partial void DeleteSupplier(Supplier instance);
    #endregion
		
		public TSQLDataContext() : 
				base(global::LINQCrud.Properties.Settings.Default.TSQLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Supplier> Suppliers
		{
			get
			{
				return this.GetTable<Supplier>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Production.LinqRead")]
		public ISingleResult<LinqReadResult> LinqRead()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LinqReadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Production.LinqInsert")]
		public int LinqInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(40)")] string companyname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string contactname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string contacttitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string region, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string postalcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(24)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(24)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Production.LinqUpdate")]
		public int LinqUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> supplierid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string contactname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string contacttitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string region, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string postalcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(24)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(24)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supplierid, contactname, contacttitle, address, city, region, postalcode, country, phone, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Production.LinqDelete")]
		public int LinqDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> supplierid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supplierid);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Production.Suppliers")]
	public partial class Supplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _supplierid;
		
		private string _companyname;
		
		private string _contactname;
		
		private string _contacttitle;
		
		private string _address;
		
		private string _city;
		
		private string _region;
		
		private string _postalcode;
		
		private string _country;
		
		private string _phone;
		
		private string _fax;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsupplieridChanging(int value);
    partial void OnsupplieridChanged();
    partial void OncompanynameChanging(string value);
    partial void OncompanynameChanged();
    partial void OncontactnameChanging(string value);
    partial void OncontactnameChanged();
    partial void OncontacttitleChanging(string value);
    partial void OncontacttitleChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OnpostalcodeChanging(string value);
    partial void OnpostalcodeChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    #endregion
		
		public Supplier()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplierid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int supplierid
		{
			get
			{
				return this._supplierid;
			}
			set
			{
				if ((this._supplierid != value))
				{
					this.OnsupplieridChanging(value);
					this.SendPropertyChanging();
					this._supplierid = value;
					this.SendPropertyChanged("supplierid");
					this.OnsupplieridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this.OncompanynameChanging(value);
					this.SendPropertyChanging();
					this._companyname = value;
					this.SendPropertyChanged("companyname");
					this.OncompanynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactname", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string contactname
		{
			get
			{
				return this._contactname;
			}
			set
			{
				if ((this._contactname != value))
				{
					this.OncontactnameChanging(value);
					this.SendPropertyChanging();
					this._contactname = value;
					this.SendPropertyChanged("contactname");
					this.OncontactnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacttitle", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string contacttitle
		{
			get
			{
				return this._contacttitle;
			}
			set
			{
				if ((this._contacttitle != value))
				{
					this.OncontacttitleChanging(value);
					this.SendPropertyChanging();
					this._contacttitle = value;
					this.SendPropertyChanged("contacttitle");
					this.OncontacttitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(15)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="NVarChar(10)")]
		public string postalcode
		{
			get
			{
				return this._postalcode;
			}
			set
			{
				if ((this._postalcode != value))
				{
					this.OnpostalcodeChanging(value);
					this.SendPropertyChanging();
					this._postalcode = value;
					this.SendPropertyChanged("postalcode");
					this.OnpostalcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(24)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class LinqReadResult
	{
		
		private int _supplierid;
		
		private string _companyname;
		
		private string _contactname;
		
		private string _contacttitle;
		
		private string _address;
		
		private string _city;
		
		private string _region;
		
		private string _postalcode;
		
		private string _country;
		
		private string _phone;
		
		private string _fax;
		
		public LinqReadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplierid", DbType="Int NOT NULL")]
		public int supplierid
		{
			get
			{
				return this._supplierid;
			}
			set
			{
				if ((this._supplierid != value))
				{
					this._supplierid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this._companyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactname", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string contactname
		{
			get
			{
				return this._contactname;
			}
			set
			{
				if ((this._contactname != value))
				{
					this._contactname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contacttitle", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string contacttitle
		{
			get
			{
				return this._contacttitle;
			}
			set
			{
				if ((this._contacttitle != value))
				{
					this._contacttitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(15)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="NVarChar(10)")]
		public string postalcode
		{
			get
			{
				return this._postalcode;
			}
			set
			{
				if ((this._postalcode != value))
				{
					this._postalcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(24)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this._fax = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
